#index:
#    path: /
#    controller: App\Controller\DefaultController::index

_wordpress:
  resource: "@WordpressBundle/config/routing.php"

#home:
#  path: /
#  controller: App\Controller\HomeController::index
